<?php

$title = 'My users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new User</a>
</p>

<table class="table">
<tr>
    <th>username</th>
    <th>email</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($User->username) ?></td>
        <td><?= $this->escapeHtml($User->email) ?></td>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $User->id]) ?>">Edit</a>
            <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $User->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>